### 4.2. `service.yaml`

apiVersion: v1
kind: Service
metadata:
  name: miapp-service
spec:
  selector:
    app: miapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
