apiVersion: v1            # Specifies the API version being used, which is "v1" for this Service.
kind: Service             # Specifies the type of Kubernetes resource, which is a Service in this case.
metadata:
  name: nginx-service     # Name of the Service.
spec:
  selector:               # Selector to match with Pods for load-balancing traffic.
    app: nginx            # Labels used for selecting Pods. Traffic will be forwarded to Pods with the label "app: nginx".
  ports:                  # List of ports that the Service exposes.
  - protocol: TCP         # Protocol used for the port (TCP in this case).
    port: 80              # Port on the Service through which it will be accessed externally.
    targetPort: 80        # Port on the Pods to which traffic will be forwarded.
