version: '3.3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus-docker
    hostname: nexus-docker
    restart: always
    ports: 
      - 8088:8081
    volumes:
      - nexus-data:/nexus-data
volumes:
  nexus-data:
    